### ISSUE TITLE
[BUG] o_proj in lora cause mem error in multi GPUs env 

### ISSUE THREAD

**Issue by laoda513** [turboderp/exllama#141] opened 2023-07-09 03:43 UTC
Currently, the lora with o_proj could cause error if the model is loaded by multi GPUs

Both AutoGPTQ and alpaca for lora 4bit can reproduce this.
For example, using AutoGPTQ train the lora using 
```
target_module=  ["q_proj", "o_proj", "v_proj"]
model = llama7B
```
and  run test_benchmakr_inference.py with:
`gpu_split = '3,3,3' ` or ‘2，2，2，2’  (with 4,4 is ok，not sure why)
could cause the error:
`Traceback (most recent call last):
  File ".../exllama/test_benchmark_inference.py", line 214, in <module>
    logits = next_logits(next_id, lora)
  File ".../exllama/test_benchmark_inference.py", line 41, in next_logits
    n_logits = model.forward(input_ids[:, a:b], cache, last_id_only, lora = apply_lora, input_mask = input_mask)
  File ".../exllama/model.py", line 850, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File ".../exllama/model.py", line 929, in _forward
    hidden_states = _move_tensor(hidden_states, device, "hidden_states", self.config)
  File ".../exllama/model.py", line 631, in _move_tensor
    return tensor.to(new_device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

train the lora using 
```
target_module= ["q_proj", "k_proj", "o_proj"]
model = llama65B
```
`gpu_split ='10,10,10,10' 
show the same error

And with 
`target_module=["q_proj", "k_proj", "v_proj", "gate_proj", "up_proj", "down_proj"] (no o_proj)`
everything just works fine.

BTW， I found exllama lora also support mlp and self_attn in source code.
Are theses two also linear and trainable by lora?

**Comment by jmoney7823956789378** [comment] 2023-07-09 03:46
The cuda memory error is a common one. I have not found it to be specifically caused by anything, as it seems to go away if I restart the docker container.

**Comment by laoda513** [comment] 2023-07-09 03:49
> The cuda memory error is a common one. I have not found it to be specifically caused by anything, as it seems to go away if I restart the docker container.

May we are facing the different issuse....

I have test this much and can reprodce this 100%.

**Comment by turboderp** [comment] 2023-07-09 10:39
`mlp` and `self_attn` aren't individual layers that can be targeted, no. They're just referenced while traversing the model hierarchy to find the right target layer. I'll try testing with an o_proj adapter in multi-GPU to see if I can reproduce this, later.

**Comment by turboderp** [comment] 2023-07-09 12:53
I was able to reproduce it, and it does appear like there was a missing context switch in part of the fused attention function. Not sure why it only shows up when a LoRA is applied to that part, but I've pushed a fix anyway.

**Comment by laoda513** [comment] 2023-07-12 01:09
> I was able to reproduce it, and it does appear like there was a missing context switch in part of the fused attention function. Not sure why it only shows up when a LoRA is applied to that part, but I've pushed a fix anyway.

I've tested and seems works fine.

**Closed** 2023-07-12 01:09 UTC
