### ISSUE TITLE
"fatal error LNK1104: cannot open file 'python310.lib'" + Solution (Windows)

### ISSUE THREAD

**Issue by JLuke73** [turboderp/exllama#76] opened 2023-06-20 02:04 UTC
I installed exllama on a secondary drive, then tried to install dependencies both inside a venv and on the root folder. In ever case I got a long error when I tried to run the test (`python test_benchmark_inference.py -d <path_to_model_files> -p -ppl`), including:

`fatal error LNK1104: cannot open file 'python310.lib'`

The solution was to **copy** the `python310.lib` file from `Program Files\Python310\libs` and **paste** it into `\venv\Scripts\libs`. Note I had to make that directory myself.

**Comment by turboderp** [comment] 2023-06-20 20:42
So I haven't heard about this issue before, leading me to think there's something in your ENV not set up correctly. The linker should be able to find `python310.lib` but I'm not sure what that process looks like on Windows. Maybe @EyeDeck knows more?

**Comment by JLuke73** [comment] 2023-06-20 20:45
I believe the cause was installing Exllama on a different drive letter (S) than my Windows/Python install (C), and the script assuming Python would be accessible from the current drive letter. I've encountered this before -- a similar bug was patched in both oogabooga's webui and auto1111's Stable Diffusion webui, though they may have presented differently.

**Comment by Panchovix** [comment] 2023-06-20 23:08
I can confirm that this happened to me as well. I think when installing Python, we missed an option of about some extra variables in the advanced options.

**Comment by EyeDeck** [comment] 2023-06-21 04:51
If I'm not mistaken (and I may be), we're relying on Torch to find the right directory here:
https://github.com/pytorch/pytorch/blob/e737a8486f2b38c699d6890be295dd6e6d6417ea/torch/utils/cpp_extension.py#L1654

```python
    if IS_WINDOWS:
        python_path = os.path.dirname(sys.executable)
        python_lib_path = os.path.join(python_path, 'libs')
```

So, if you opened a Python interpreter in the same environment (or venv/conda environment/etc) as exllama, you could manually check like:
```python
>>> import sys, os; os.path.join(os.path.dirname(sys.executable), 'libs')
'G:\\miniconda\\envs\\tgwui\\libs'
```
and that path _should_ have `python310.lib`, or possibly some other version like `python39.lib` or `python311.lib` or whatever.

It doesn't look like that's valid in a regular Python venv though, for example doing that in an existing venv instance from Auto1111's webui: 
```
import sys, os; os.path.join(os.path.dirname(sys.executable), 'libs')
'G:\\stable-diffusion-webui\\venv\\Scripts\\libs
```
and in that case the `libs` directory doesn't even exist.

Not sure what the cleanest way to handle this is without doing some research.

**Comment by EyeDeck** [comment] 2023-06-21 07:20
I thought of less stupid code to fix this, if anyone wants to test out #89 I'd appreciate it.

**Comment by TechnotechYT** [comment] 2023-06-21 09:19
I also ran into a number of issues running ExLlama in a venv, most of which were due to the fact the activate script was wrong (oops).
This issue was one of them

**Comment by EyeDeck** [comment] 2023-06-22 19:50
Should be fixed after the latest commit.

**Comment by turboderp** [comment] 2023-06-23 16:41
I'll assume this is fixed and close the issue for now.

**Closed by turboderp** 2023-06-23 16:41 UTC
